apiVersion: v1
kind: Service
metadata:
  labels:
    app: taco-angular
  name: taco-angular
spec:
  ports:
    - nodePort: 32001
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: taco-angular
  type: NodePort
